# Numpy
Numpy is a core library for scientific computing in Python. It provides a high-performance multidimensional array objects, such as matrices, and built-in functions to work on these arrays. Numpy arrays are commonly used to store matrices. Numpy built-in functions are commonly used to perform operations on matrices (transpose, dot product, etc.). 

### 1) Defining a Numpy array
Array is an ordered sequence of elements. The elements are indexed and should be of the same type. 

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])

In [3]:
type(arr)

numpy.ndarray

We use method shape to obtain the size of the array.

In [ ]:
arr.shape

We will use numpy arrays to compute with matrices. First, we can store $\begin{pmatrix} 4 & 6 &8 \\ 1 & 3 & 9 \\ 2 & 3 & 2 \\ 0 &1 &7  \end{pmatrix}$ as follows:

In [ ]:
matrix = np.array([[4,6,8],[1,3,9],[2,3,2],[0,1,7]]) 

matrix is a 2D array with 4 rown and 3 columns.

In [ ]:
matrix.shape

#### 1.1) Datatypes 

All the elements of an array must have the same type.

In [ ]:
arr1 = np.array([1.,2,3])

In [ ]:
arr1.dtype

In [ ]:
arr2 = np.array([1,2.,3])

In [ ]:
arr2.dtype

In [ ]:
arr3 = np.array([2.,"Is this an array of string?",3])

In [ ]:
arr3.dtype

In [ ]:
type(arr3[1])

In [ ]:
arr2[1]

As you can see, python forces all the elements to be of the same type. For example, in arr3, python changes the type of all the elements to string. To explicity specify the type of your array, use argument dtype as follows: 

In [ ]:
arr1 = np.array([1,2.23,3],dtype=np.int64)

In [ ]:
arr1[1]

In [ ]:
arr2 = np.array([1,2.,3],dtype=np.float64)

In [ ]:
arr2[0]

In [ ]:
arr3 = np.array(["Is this an array of string?",2.,3],dtype=np.str)

In [ ]:
arr3[1]

#### 1.2) Indexing and slicing
Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, we must specify a slice for each dimension of the array.

In [ ]:
matrix

In [ ]:
matrix[0,1]

In [ ]:
matrix[3]

Using slicing, we extract the second column. matrix[:,1] means for all the rows (indicated by ":"), take the element at index 1.

In [ ]:
matrix[:,1]

Using slicing, we extract the second and third row. matrix[1:3,:] means for all the rows (indicated by ":"), take the element at index 1.

In [ ]:
matrix[1:3,:]

We can use the row index and column index in integer array indexing as follows:

In [ ]:
matrix[[0,2],[1,2]] # we extract elements at index (0,1) and (2,2).

In [ ]:
matrix[[0,1,2,3],[1,1,1,1]] 

Note that the indexing and slicing returns Numpy array. Indexing and slicing allow to build new arrays from existing ones.

In [ ]:
vector = matrix[:,1]

In [ ]:
vector

#### 1.3) Filling-in 
Numpy provides functions to fill in arrays.

In [ ]:
np.ones((5,5),dtype=np.int64) # make a matrix of size (5,5) and fill it with 1

In [ ]:
np.zeros((4,3),dtype=np.int64)

In [ ]:
np.eye(3)

To fill-in a matrix with random values, one option is to select values from a continuous uniform distribution over the interval [0, 1).

In [ ]:
np.random.random((3,5))

To select values over the interval [10,100)

In [ ]:
(100 - 10) * np.random.random((3,5)) + 10

randn generates an array whose values are drawn from a standard Gaussian distribution $N(0,1)$. 

In [ ]:
np.random.randn(3,5)

For random samples from $N(\mu, \sigma^2)$, use $\sigma$ * np.random.randn(3,4) + $\mu$.

We use "zeros_like" or "ones_likes" to create matrices of the same size and fill it with 0 or 1, respectively.

In [ ]:
np.zeros_like(matrix)

In [ ]:
np.ones_like(matrix)

### 2) Arithmetic
Basic mathematical functions operate **elementwise** on arrays, and are available both as built-in function and arithmetic operator overloading. 

Let V and U be 3D vectors $\begin{pmatrix}-1 \\ 3 \\ 4/5\end{pmatrix}$ and $\begin{pmatrix}6 \\ 0 \\ 3\end{pmatrix}$, respectively.  

In [ ]:
V = np.array([[-1],[3],[4/5]],dtype=np.float64)

In [ ]:
U = np.array([[6],[0],[3]],dtype=np.float64)

We can perform addition and multiplication by a scalar:

In [ ]:
U + 2*V # using operator overloading

In [ ]:
np.add(U,np.multiply(2,V)) # using Numpy built-in functions

Note that "*" and "np.multiply" is elementwise multiplication (not matrix maltiplication or dot product).

In [ ]:
V*U

In [ ]:
np.multiply(U,V)

In [ ]:
V*U + 3

Mathematical functions also operate elementwise on arrays.

In [ ]:
m = np.array([[4,5.8],[3.2,1.4]])

In [ ]:
np.log(m)

In [ ]:
np.sin(m)

In [ ]:
np.exp(m)

In [ ]:
np.power(m,3)

### 3) Matrix operations

#### 3.1) Dot product
Following the previous example, we want to compute the rotation of vectors U and V by an angle $\theta$ across the z-axis. We compute the dot product of the matrix $\begin{pmatrix}cos(\theta) & -sin(\theta) & 0 \\ sin(\theta) & cos(\theta) \\ 0 & 0 & 1\end{pmatrix}$ and the vectors U and V.

In [ ]:
import math as m

In [ ]:
teta = m.pi/6

In [ ]:
rotz = np.array([[m.cos(teta),-m.sin(teta),0],[m.sin(teta),m.cos(teta),0],[0,0,1]])

In [ ]:
rotz

In [ ]:
np.dot(rotz,V)

In [ ]:
np.dot(rotz,U)

In [ ]:
rotz.dot(U)

#### 3.2) Summation

In [ ]:
matrix

In [ ]:
matrix.sum() # computes the sum of all the elements

In [ ]:
np.sum(matrix)

In [ ]:
matrix.sum(axis=0) # compute the sum of the columns

In [ ]:
np.sum(matrix,axis=0)

In [ ]:
matrix.sum(axis=1) # compute the sum of the rows

In [ ]:
np.sum(matrix,axis=1)

#### 3.3) Transpose

In [ ]:
matrix.T

In [ ]:
np.transpose(matrix)

In [ ]:
(matrix.T).T == matrix

In [ ]:
np.equal(matrix.T.T,matrix)

### 4) Linear algebra

In [ ]:
x = np.array([[4,2,1],[2,6,3],[2,4,5]])

In [ ]:
np.linalg.det(x)

In [ ]:
np.linalg.eigvals(x)

To solve the system of equations 3 * x0 + x1 = 9 and x0 + 2 * x1 = 8.

In [ ]:
a = np.array([[3,1],[1,2]])

In [ ]:
b = np.array([9,8])

In [ ]:
np.linalg.solve(a,b)

### 4) List vs. array

Both list and array are also mutable objects.

In [ ]:
m = np.array([[2,3],[4,5]])

In [ ]:
m[1,1] = 8

In [ ]:
m

In [ ]:
id(m)

In [ ]:
p = m

In [ ]:
id(p)

Unlike list, elements of array must have the same type.

In [ ]:
m[1,1] = "Can I add a string?"

An array allows arithmetic operations, whereas a list does not.

In [ ]:
m / np.sum(m)

In [ ]:
[2,4,5]/2

Like list, we can iterate over an array.

In [ ]:
for r in m:
    print(np.sum(r))

### 5) Boradcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
def add_arrays_of_different_size(x,vector):
    y = np.empty_like(x)   # Create an empty matrix with the same shape as x

    # Add the vector v to each row of the matrix x with an explicit loop
    for i in range(len(vector)):
        y[i, :] = x[i, :] + vector

    return y

In [ ]:
matrix

In [ ]:
add_arrays_of_different_size(matrix, [-2,3,1])

This works; however when the matrix x is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix x is equivalent to stacking multiple copies of v vertically, this is operation is called **broadcasting**. Numpy broadcasting allows us to perform this computation without using loop or creating multiple copies of v.

In [ ]:
matrix + [-2,3,1]

**Practice**: Explain the results of the following broadcasting.

In [ ]:
matrix + 1

In [ ]:
matrix * [[0],[2],[5],[-2]]

In [ ]:
matrix * [[9],[3]]

### 6) Problem: Binary logistic regression
Binary logistic regression is a machine learning method used for prediction like any other regression analyses. Logistic regression is suitable for **classification problems** because it is suitable to explain the relationship between features $x_1$, $\ldots$, $x_n$ and a **binary output** $y$. For instance, whether features $x_1$, $\ldots$, $x_n$ describe **class A** or not. Estimation $\hat{y}$ is regarded as a probability of a class.

Suppose that we have a trained data using binary logistic regression. Given a new data $x_1$, $x_2$ and $x_3$, write python code, using Numpy, to compute the estimation $\hat{y}$.

<img src="images/LRegression.png">

where:
- $x_1$, $x_2$ and $x_3$ are features.
- $w_1$, $w_2$ and $w_3$ are the weights. 
- $b$ is the bias
- $\sigma$ is the sigmoid function, i.e. $\sigma(z) = \frac{1}{1+e^{-z}}$, that gives probability $\hat{y} \in [0,1]$


#### 6.1) Sigmoid function

In [4]:
def sigmoid(z):
    ### START CODE HERE ### (1 line of code)
    s = 1/(1+np.exp(-z))
    ### END CODE HERE ###
    
    return s

In [5]:
sigmoid(3)

0.9525741268224334

In [6]:
sigmoid(np.array([0,2]))

array([0.5       , 0.88079708])

#### 6.2) Vectorization
Suppose we want to perform prediction for 10 thousand of data $X_1$, $\ldots$, $X_{10000}$. Data $X_i$ has three features $x_{1i}$, $x_{2i}$ and $x_{3i}$, where $1\leq i \leq 3$. We could iterate prediction $\sigma(\sum^{3}_{i=1}w_{ij} x_{ij} + b_j)$, using for-loop, 10000 times! However, a much faster approach is to use Numpy arrays. We first collect all data in arrays/matrices and this step is called vectorization. 


What is the shape of the matrix **X** of 10000 input data? 

In [7]:
X = np.ones((3,10000)) # enter the size

In [8]:
X.shape

(3, 10000)

What is the size of vector **W** of weights?

In [9]:
W = np.zeros((3,1)) # enter the size

In [10]:
W

array([[0.],
       [0.],
       [0.]])

Guess the size of $\hat{y}$.

In [11]:
hat_y = np.random.random(10000)

In [12]:
hat_y

array([0.25139286, 0.89340023, 0.01980851, ..., 0.93877168, 0.47964201,
       0.35373334])

#### 6.3) Linear function
Implement the linear function in the above picture, i.e. $\sum^{3}_{i=1}w_{ij} x_{ij} + b_j$. **The function should be able to compute for more than one data at once**. To that end, use the appropriate matrix operation.

In [16]:
def linear_fct(X, W, b):
    ### START CODE HERE ### (1 line of code)
    Z = np.dot(W.T,X)+b
    ### END CODE HERE ###
    
    return Z

#### 6.4) Estimation
Function estimation (i) computes the estimation $\hat{y}$ and (ii) classify the data, e.g. if $\hat{y} \geq 0.7$ then the data is in class 1 otherwise class 0. 

In [13]:
def estimation(Z):

    ### START CODE HERE ### (~ 2 lines of code)
    y_hat = sigmoid(Z)
    bclass = y_hat >= 0.7
    ### END CODE HERE ###
    
    return y_hat, bclass

#### 6.5) Prediction
Compute the prediction of data X using the functions you implemented so far.

In [14]:
w, b, X = np.array([[1.],[2.]]), 2., np.array([[1.,2.,-1.],[3.,4.,-3.2]])

In [17]:
Z = linear_fct(X,w,b)

In [18]:
estimation(Z)

(array([[0.99987661, 0.99999386, 0.00449627]]), array([[ True,  True, False]]))